version: '2'

services:

  # main application
  nefarious:
    labels:
    - com.centurylinklabs.watchtower.enable=true
    image: lardbit/nefarious
    restart: always
    ports:
    - "8000:80"
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
    volumes:
    # persistent named volume for sqlite database
    - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
    - redis
    - jackett
    - celery

  # background task service
  celery:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lardbit/nefarious
    restart: always
    entrypoint: /env/bin/celery -A nefarious worker --beat --loglevel=INFO
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
    volumes:
    # persistent named volume for sqlite database
    - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
      - redis

  # in-memory database
  redis:
    image: redis
    restart: always
    # TODO - don't expose outside of docker network
    ports:
    - "6379:6379"

  # torrent indexer service
  jackett:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: linuxserver/jackett
    mem_limit: 200m
    restart: always
    ports:
      - "9117:9117"
    logging:
      options:
        max-size: 10m
    volumes:
      - jackett-config:/config

  transmission:
    image: linuxserver/transmission
    volumes:
      - transmission-config:/config
      # update this path to point to where you want things downloaded
      - .:/downloads
    ports:
      - "9091:9091"

  # auto update service
  # https://github.com/v2tec/watchtower
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: --label-enable --cleanup
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nefarious-db:
  jackett-config:
  transmission-config:
